<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/BuildingBlocks/MusicPlayer2-Avalonia.Infrastructure.Desktop/MusicPlayer2-Avalonia.Infrastructure.Desktop.csproj" />
  </ItemGroup>
</Project>
