// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicPlayer2_Avalonia.Infrastructure.Persistence;

#nullable disable

namespace MusicPlayer2_Avalonia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MusicPlayerDbContext))]
    [Migration("20260908143035_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MusicPlayer2_Avalonia.Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AlbumArtistId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlbumArtistId");

                    b.HasIndex("Title", "AlbumArtistId");

                    b.ToTable("Albums", (string)null);
                });

            modelBuilder.Entity("MusicPlayer2_Avalonia.Domain.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Artists", (string)null);
                });

            modelBuilder.Entity("MusicPlayer2_Avalonia.Domain.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playlists", (string)null);
                });

            modelBuilder.Entity("MusicPlayer2_Avalonia.Domain.Entities.PlaylistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("PlaylistId", "Position")
                        .IsUnique();

                    b.ToTable("PlaylistItems", (string)null);
                });

            modelBuilder.Entity("MusicPlayer2_Avalonia.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SourceFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SourceLastWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AudioProperties", "MusicPlayer2_Avalonia.Domain.Entities.Track.AudioProperties#AudioProperties", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("BitDepth")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BitDepth");

                            b1.Property<int>("BitrateKbps")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BitrateKbps");

                            b1.Property<int>("Channels")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Channels");

                            b1.Property<long>("Duration")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AudioDurationTicks");

                            b1.Property<int>("SampleRateHz")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SampleRateHz");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Position", "MusicPlayer2_Avalonia.Domain.Entities.Track.Position#TrackPosition", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("DiscNumber")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DiscNumber");

                            b1.Property<int>("TrackNumber")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TrackNumber");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Source", "MusicPlayer2_Avalonia.Domain.Entities.Track.Source#LocalAudioFile", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("TEXT")
                                .HasColumnName("SourcePath");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Title");

                    b.ToTable("Tracks", (string)null);
                });

            modelBuilder.Entity("MusicPlayer2_Avalonia.Domain.Entities.Album", b =>
                {
                    b.HasOne("MusicPlayer2_Avalonia.Domain.Entities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("AlbumArtistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicPlayer2_Avalonia.Domain.Entities.PlaylistItem", b =>
                {
                    b.HasOne("MusicPlayer2_Avalonia.Domain.Entities.Playlist", null)
                        .WithMany("PlaylistItems")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicPlayer2_Avalonia.Domain.Entities.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicPlayer2_Avalonia.Domain.Entities.Track", b =>
                {
                    b.HasOne("MusicPlayer2_Avalonia.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MusicPlayer2_Avalonia.Domain.Entities.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicPlayer2_Avalonia.Domain.Entities.Artist", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicPlayer2_Avalonia.Domain.Entities.Playlist", b =>
                {
                    b.Navigation("PlaylistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
