<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/BuildingBlocks/MusicPlayer2-Avalonia/MusicPlayer2-Avalonia.csproj" />
    <PackageReference Include="Avalonia.Headless" />
  </ItemGroup>
</Project>
